### ISSUE TITLE
TypeError: Function expected

### ISSUE THREAD

**Issue by Turbo87** [tchak/ember-url#4]
We're seeing the following error on Sentry inside of `ember-url` with Edge 12 on Windows 10:

```js
TypeError: Function expected
  at testURL(addon-tree-output/url/index.js:14:0)
  at n.prototype.exports(vendor/loader/loader.js:106:0)
  at reified(vendor/loader/loader.js:143:0)
  at this(vendor/loader/loader.js:130:0)
  at this(vendor/loader/loader.js:104:0)
  at pending(vendor/loader/loader.js:27:0)
  at _extractDefaultExport(addon-tree-output/ember-resolver/resolvers/classic/index.js:392:0)
  at i(addon-tree-output/ember-resolver/resolvers/classic/index.js:113:0)
```

<img width="1002" alt="bildschirmfoto 2017-11-16 um 09 20 02" src="https://user-images.githubusercontent.com/141300/32880837-5fd8364c-caaf-11e7-8339-a45824aa9c9f.png">

**Comment by tchak** [comment]
Crap. I just run tests on Edge 13 (the lowest available on saucelabs) and it works...
